### ISSUE TITLE
Apache Maven

### ISSUE THREAD

**Issue by FilippoMito** [notsojug/jug-material#28]
What is it: introduction, build phases, plugins and some useful examples

**Comment by FilippoMito** [comment]
@civitz review slides please

**Comment by civitz** [comment]
A Build Phase is Made Up of Plugin Goals => there's a bit too much text there... 

In "Plugins" and slide also. 

A little summary before presenting plugins would be great. Also a bullet list of plugins after them

**Comment by civitz** [comment]
Otherr than that, looks good to me

**Comment by FilippoMito** [comment]
Fixed in 5f0def4
